export const physicalSkills = [
    {name: "Fliegen", properties: "MU/IN/GE", be: "ja", group: "B"},
    {name: "Gaukeleien", properties: "MU/CH/FF", be: "ja", group: "A"},
    {name: "Klettern", properties: "MU/GE/KK", be: "ja", group: "B"},
    {name: "Körperbeherrschung", properties: "GE/GE/KO", be: "ja", group: "D"},
    {name: "Kraftakt", properties: "KO/KK/KK", be: "ja", group: "B"},
    {name: "Reiten", properties: "CH/GE/KK", be: "ja", group: "B"},
    {name: "Schwimmen", properties: "GE/KO/KK", be: "ja", group: "B"},
    {name: "Selbstbeherrschung", properties: "MU/MU/KO", be: "nein", group: "D"},
    {name: "Singen", properties: "KL/CH/KO", be: "evtl", group: "A"},
    {name: "Sinnesschärfe", properties: "KL/IN/IN", be: "evtl", group: "D"},
    {name: "Tanzen", properties: "KL/CH/GE", be: "ja", group: "A"},
    {name: "Taschendiebstahl", properties: "MU/FF/GE", be: "ja", group: "B"},
    {name: "Verbergen", properties: "MU/IN/GE", be: "ja", group: "C"},
    {name: "Zechen", properties: "KL/KO/KK", be: "nein", group: "A"},
];

export const socialSkills = [
    {name: "Bekehren & Überzeugen", properties: "MU/KL/CH", be: "nein", group: "B"},
    {name: "Betören", properties: "MU/CH/CH", be: "evtl", group: "B"},
    {name: "Einschüchtern", properties: "MU/IN/CH", be: "nein", group: "B"},
    {name: "Etikette", properties: "KL/IN/CH", be: "evtl", group: "B"},
    {name: "Gassenwissen", properties: "KL/IN/CH", be: "evtl", group: "C"},
    {name: "Menschenkenntnis", properties: "KL/IN/CH", be: "nein", group: "C"},
    {name: "Überreden", properties: "MU/IN/CH", be: "nein", group: "C"},
    {name: "Verkleiden", properties: "IN/CH/GE", be: "evtl", group: "B"},
    {name: "Willenskraft", properties: "MU/IN/CH", be: "nein", group: "D"},
];

export const natureSkills = [
    {name: "Fährtensuchen", properties: "MU/IN/GE", be: "ja", group: "C"},
    {name: "Fesseln", properties: "KL/FF/KK", be: "evtl", group: "A"},
    {name: "Fischen & Angeln", properties: "FF/GE/KO", be: "evtl", group: "A"},
    {name: "Orientierung", properties: "KL/IN/IN", be: "nein", group: "B"},
    {name: "Pflanzenkunde", properties: "KL/FF/KO", be: "evtl", group: "C"},
    {name: "Tierkunde", properties: "MU/MU/CH", be: "ja", group: "C"},
    {name: "Wildnisleben", properties: "MU/GE/KO", be: "ja", group: "C"},
];

export const scienceSkills = [
    {name: "Brett- & Glücksspiel", properties: "KL/KL/IN", be: "nein", group: "A"},
    {name: "Geographie", properties: "KL/KL/IN", be: "nein", group: "B"},
    {name: "Geschichtswissen", properties: "KL/KL/IN", be: "nein", group: "B"},
    {name: "Götter & Kulte", properties: "KL/KL/IN", be: "nein", group: "B"},
    {name: "Kriegskunst", properties: "MU/KL/IN", be: "nein", group: "B"},
    {name: "Magiekunde", properties: "KL/KL/IN", be: "nein", group: "C"},
    {name: "Mechanik", properties: "KL/KL/FF", be: "nein", group: "B"},
    {name: "Rechnen", properties: "KL/KL/IN", be: "nein", group: "A"},
    {name: "Rechtskunde", properties: "KL/KL/IN", be: "nein", group: "A"},
    {name: "Sagen & Legenden", properties: "KL/KL/IN", be: "nein", group: "B"},
    {name: "Sphärenkunde", properties: "KL/KL/IN", be: "nein", group: "B"},
    {name: "Sternkunde", properties: "KL/KL/IN", be: "nein", group: "A"},
];

export const craftSkills = [
    {name: "Alchimie", properties: "MU/KL/FF", be: "ja", group: "C"},
    {name: "Boote & Schiffe", properties: "FF/GE/KK", be: "ja", group: "B"},
    {name: "Fahrzeuge", properties: "CH/FF/KO", be: "ja", group: "A"},
    {name: "Handel", properties: "KL/IN/CH", be: "nein", group: "B"},
    {name: "Heilkunde Gift", properties: "MU/KL/IN", be: "ja", group: "B"},
    {name: "Heilkunde Krankheiten", properties: "MU/IN/KO", be: "ja", group: "B"},
    {name: "Heilkunde Seele", properties: "IN/CH/KO", be: "nein", group: "B"},
    {name: "Heilkunde Wunden", properties: "KL/FF/FF", be: "ja", group: "D"},
    {name: "Holzbearbeitung", properties: "FF/GE/KK", be: "ja", group: "B"},
    {name: "Lebensmittelbearbeitung", properties: "IN/FF/FF", be: "ja", group: "A"},
    {name: "Lederbearbeitung", properties: "FF/GE/KO", be: "ja", group: "B"},
    {name: "Malen & Zeichnen", properties: "IN/FF/FF", be: "ja", group: "A"},
    {name: "Metallbearbeitung", properties: "FF/KO/KK", be: "ja", group: "C"},
    {name: "Musizieren", properties: "CH/FF/KO", be: "ja", group: "A"},
    {name: "Schlösserknacken", properties: "IN/FF/FF", be: "ja", group: "C"},
    {name: "Steinbearbeitung", properties: "FF/FF/KK", be: "ja", group: "A"},
    {name: "Stoffbearbeitung", properties: "KL/FF/FF", be: "ja", group: "A"},
];

export const fightSkills = [
    {name: "Armbrüste", properties: "FF", be: "ja", group: "B", fk: true, pa: false},
    {name: "Blasrohre", properties: "FF", be: "ja", group: "B", fk: true, pa: false},
    {name: "Bögen", properties: "FF", be: "ja", group: "C", fk: true, pa: false},
    {name: "Diskusse", properties: "FF", be: "ja", group: "C", fk: true, pa: false},
    {name: "Dolche", properties: "GE", be: "ja", group: "B", fk: false, pa: true},
    {name: "Energiewaffen", properties: "FF", be: "ja", group: "D", fk: true, pa: false},
    {name: "Fächer", properties: "GE", be: "ja", group: "C", fk: false, pa: true},
    {name: "Fechtwaffen", properties: "GE", be: "ja", group: "C", fk: false, pa: true},
    {name: "Feuerspeien", properties: "FF", be: "ja", group: "B", fk: true, pa: false},
    {name: "Hiebwaffen", properties: "KK", be: "ja", group: "C", fk: false, pa: true},
    {name: "Kettenwaffen", properties: "KK", be: "ja", group: "C", fk: false, pa: false},
    {name: "Lanzen", properties: "KK", be: "ja", group: "B", fk: false, pa: true},
    {name: "Peitschen", properties: "FF", be: "ja", group: "B", fk: false, pa: false},
    {name: "Raufen", properties: "GE/KK", be: "ja", group: "B", fk: false, pa: true},
    {name: "Schilde", properties: "KK", be: "ja", group: "C", fk: false, pa: true},
    {name: "Schleudern", properties: "FF", be: "ja", group: "B", fk: true, pa: false},
    {name: "Schwerter", properties: "GE/KK", be: "ja", group: "C", fk: false, pa: true},
    {name: "Spießwaffen", properties: "KK", be: "ja", group: "C", fk: false, pa: false},
    {name: "Stangenwaffen", properties: "GE/KK", be: "ja", group: "C", fk: false, pa: true},
    {name: "Wurfwaffen", properties: "FF", be: "ja", group: "B", fk: true, pa: false},
    {name: "Zweihandhiebwaffen", properties: "KK", be: "ja", group: "C", fk: false, pa: true},
    {name: "Zweihandschwerter", properties: "KK", be: "ja", group: "C", fk: false, pa: true},
];